# Generated by Django 2.2.4 on 2019-08-13 17:07

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
         migrations.RunPython(fill_new_building_field),
    ]
