# Generated by Django 2.2.4 on 2019-08-15 06:00

from django.db import migrations
from django.db import IntegrityError, transaction
import phonenumbers


COUNTRY_CODE = 'RU'
COUNTRY_PHONE_CODE = 7


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_phonenumber_pure = None
        flat.save()


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, COUNTRY_CODE)
        number = phone_number.national_number
        code = phone_number.country_code
        if phonenumbers.is_valid_number(phone_number) and code == COUNTRY_PHONE_CODE:
            flat.owners_phonenumber_pure = '+{}{}'.format(code, number)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190814_1110'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
