# Generated by Django 2.2.4 on 2019-08-15 07:30

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner(name=flat.owner, phonenumber=flat.owners_phonenumber, phonenumber_pure=flat.owners_phonenumber_pure)
        owner.save()
        owner.flats.add(flat)
        owner.save()


def delete_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners, delete_owners),
    ]
